name: create-next-semver
description: 'Create next SemVer release'
inputs:
  GH_TOKEN:
    description: 'GitHub personal access token'
    required: true
    default: ''
  COMMIT_SHA:
    description: 'Commit SHA'
    required: true
    default: ''
outputs:
  release_tag:
    description: 'The tag of the created release'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GH_TOKEN }}
    - ${{ inputs.COMMIT_SHA }}
